/* eslint-disable @next/next/no-img-element */
'use client';

import React, { useEffect, useRef, useState } from "react";
import Markdown from "react-markdown";
import styles from './style.module.css';
const content = `
 # Terms of Service
 #### Latest update: Mar 11, 2024
 The following document describes the conditions of use of our Websites and Services.

TubeXChat, Inc. ("TubeXChat") is a US company whose registered office is located at 2315 Ashby Avenue,Berkeley,CA94705, USA, under the file number 7358523.

TubeXChat is pleased to give you access to TubeXChat's website (tubex.chat) ("Website","TubeX.AI"or "TubeX"), 
and related applications and resources (collectively, the "Services"). Your use of the Services is subject to the binding legal agreement set forth below ("Terms").

## Beta Software
We may provide you with beta and experimental products, features, and documentation ("Beta Software") on an early access basis. 
Beta Software is not generally available and may contain errors, defects, and inaccuracies. We provide Beta Software "as is" without any warranties and may terminate Beta Software at any time without ensuring the preservation of Beta Software data. 
Our service level agreements do not apply to Beta Software.
 If Beta Software becomes generally available, you may choose to pay for the software or stop using it. We may use your feedback on Beta Software.

## Usage of TubeX Services
You may use the TubeX.AI development platform to create software applications for your target user group to achieve your commercial objectives. 
You understand and acknowledge that the language and information generated by software applications created based on TubeX.AI are derived from user-written prompts and their Large Language Model (LLM) providers (such as OpenAI). LLM is an immature technology, and any negative consequences arising from the language and information generated are not related to TubeX.AI , especially if you commercialize the application but fail to meet your operational expectations (including but not limited to not meeting your advertising description expectations, target effect description expectations, etc.) or experience service interruptions.

The development of prompts for LLM models is the core product capability and service provided by TubeX. 
During your use of TubeX for prompt engineering, embedding, fine-tuning, and testing of LLM models, additional resource consumption may occur. By registering or starting to use TubeX, you agree to the potential consumption of resources and costs associated with the LLM algorithms of this product. You should closely monitor billing changes from third-party LLM providers. You shall bear all consequences of any abnormal consumption and billing issues that prevent you from using TubeX services normally.

## Intellectual Property
The Services, logo, interfaces, photos, Websites are owned by TubeXChat, Inc. or its licensees and protected by applicable law, 
with all rights reserved. TubeXChat takes the protection of intellectual property rights, including copyrights, very seriously. 
TubeXChat will terminate your access to, or use of, all or any part of the Services, without notice to you, if you infringe or misappropriate the intellectual property rights,
 including copyrights, of others.

## Applicable Law
The Terms are governed by the laws of the State of California, United States.
`
function TermsOfService() {

  return (
    <div className={styles.markdown}>
      <div className="mx-auto w-[800px]">
        <Markdown>{content}</Markdown>
      </div>
    </div>
  );
}

export default TermsOfService;
